export enum Permissions {
  ADMINISTRATOR = 'ADMINISTRATOR',
  MANAGE_SERVER = 'MANAGE_SERVER',
  MANAGE_CHANNELS = 'MANAGE_CHANNELS',
  KICK_MEMBERS = 'KICK_MEMBERS',
  BAN_MEMBERS = 'BAN_MEMBERS',
  CREATE_INVITES = 'CREATE_INVITES',
  SEND_MESSAGES = 'SEND_MESSAGES',
  MENTION_EVERYONE = 'MENTION_EVERYONE',
}

export const DEFAULT_PERMISSIONS = [
  Permissions.SEND_MESSAGES,
  Permissions.CREATE_INVITES
];
