export enum Permissions {
  ADMINISTRATOR = 'ADMINISTRATOR',
  MANAGE_SERVER = 'MANAGE_SERVER',
  MANAGE_ROLES = 'MANAGE_ROLES',
  MANAGE_CHANNELS = 'MANAGE_CHANNELS',
  KICK_MEMBERS = 'KICK_MEMBERS',
  BAN_MEMBERS = 'BAN_MEMBERS',
  CREATE_INVITES = 'CREATE_INVITES',
  SEND_MESSAGES = 'SEND_MESSAGES',
  VIEW_CHANNELS = 'VIEW_CHANNELS',
  READ_MESSAGE_HISTORY = 'READ_MESSAGE_HISTORY',
  MENTION_EVERYONE = 'MENTION_EVERYONE',
}

export const DEFAULT_PERMISSIONS = [
  Permissions.VIEW_CHANNELS,
  Permissions.SEND_MESSAGES,
  Permissions.READ_MESSAGE_HISTORY,
  Permissions.CREATE_INVITES
];
